"""Add order items and tracking tables

Revision ID: 97e39d02746a
Revises: c5d9e9ef3448
Create Date: 2026-09-05 16:04:27.184204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97e39d02746a'
down_revision: Union[str, None] = 'c5d9e9ef3448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###